# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       make
Summary:    A GNU tool which simplifies the build process for users
Version:    3.81
Release:    1
Group:      Development/Tools
License:    GPLv2+
URL:        http://www.gnu.org/software/make/
Source0:    ftp://ftp.gnu.org/gnu/make/make-%{version}.tar.bz2
Source100:  make.yaml
Patch0:     make-3.79.1-noclock_gettime.patch
Patch1:     make-3.80-j8k.patch
Patch2:     make-3.80-getcwd.patch
Patch3:     make-3.81-err-reporting.patch
Patch4:     make-3.81-memory.patch
Patch5:     make-3.81-rlimit.patch
Patch6:     make-3.81-newlines.patch
Patch7:     make-3.81-jobserver.patch


%description
A GNU tool for controlling the generation of executables and other
non-source files of a program from the program's source files. Make
allows users to build and install packages without any significant
knowledge about the details of the build process. The details about
how the program should be built are provided for make in the program's
makefile.




%prep
%setup -q -n %{name}-%{version}

# make-3.79.1-noclock_gettime.patch
%patch0 -p1
# make-3.80-j8k.patch
%patch1 -p1
# make-3.80-getcwd.patch
%patch2 -p1
# make-3.81-err-reporting.patch
%patch3 -p1
# make-3.81-memory.patch
%patch4 -p1
# make-3.81-rlimit.patch
%patch5 -p1
# make-3.81-newlines.patch
%patch6 -p1
# make-3.81-jobserver.patch
%patch7 -p1
# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --disable-nls

make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
ln -sf make %{buildroot}%{_bindir}/gmake
ln -sf make.1 %{buildroot}%{_mandir}/man1/gmake.1
rm -rf %{buildroot}%{_infodir}
# << install post






%files
%defattr(-,root,root,-)
# >> files
%doc NEWS README COPYING AUTHORS
%{_bindir}/*
%doc %{_mandir}/man*/*
# << files


